[package]
name = "test-repo-2"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src"

[dependencies]
test-repo-1 = {git = "https://github.com/leanprover-contrib/test-repo-1", rev = "a3fd794619ee8ab0bb8dc30ebefa4af63db5403c"}
