[package]
name = "test-repo-2"
version = "0.1"
lean_version = "leanprover-community/lean:3.22.0"
path = "src"

[dependencies]
test-repo-1 = {git = "https://github.com/leanprover-contrib/test-repo-1", rev = "76287d828253814d9d29583a9ebfaa00dbdfd4b9"}
